Repository INM-6/mesocircuit-model, pull requests merged in 2023-09, with the labels that each got.

#207 Move docker file to docs/source
  docs/source/docker.rst
Labels: maintenance

#209 add files required for readthedocs
  .readthedocs.yaml
  README.md
  docs/requirements.txt
Labels: documentation, enhancement

#212 Add network sketch to README
  README.md
Labels: enhancement

#213 Add home to navigation and update acknowledgements in docs
  docs/source/acknowledgments.rst
  docs/source/conf.py
  docs/source/index.rst
Labels: documentation

#214 Add new preprint to documentation
  README.md
  docs/source/bib/mesocircuit.bib
  docs/source/citing.rst
Labels: documentation
